const express = require('express');
const router = express.Router();
const PlatformGameController = require('../controllers/PlatformGameController');
router.post('/platform-game', PlatformGameController.createPlatformGame);
router.get('/platform-game', PlatformGameController.getAllPlatformGames);
router.get('/platform-game/:id', PlatformGameController.getPlatformGameById);
router.delete('/platform-game/:id', PlatformGameController.deletePlatformGame);
router.get('/platform-games/:platformId', PlatformGameController.getGamesByPlatformId);
router.delete('/platform-game/platform/:platformId/game/:gameId', PlatformGameController.deletePlatformGameByPlatformIdAndGameId);
router.get('/platform-games/name/:platformName', PlatformGameController.getGamesByPlatformName);
module.exports = router;
